### ISSUE TITLE
when navigating back from query view to database view object is lost

### ISSUE THREAD

**Issue by anandsunderraman** [anandsunderraman/jsonsqlonline#6]
When a user pastes a JSON object in https://anandsunderraman.github.io/jsonsqlonline/#/createDB
and navigates to the query page
https://anandsunderraman.github.io/jsonsqlonline/#/queryDB
and navigates back to 
https://anandsunderraman.github.io/jsonsqlonline/#/createDB
the object is lost

**Comment by RisingGeek** [comment]
Can I work on this?

**Comment by anandsunderraman** [comment]
@RisingGeek sure please go ahead do reach out to me if you have any questions

**Comment by anandsunderraman** [comment]
we can chat at [https://t.me/jsonsql](https://t.me/jsonsql)

**Comment by RisingGeek** [comment]
I think this issue is resolved now.

**Comment by anandsunderraman** [comment]
thanks @RisingGeek
