### ISSUE TITLE
download as json feature

### ISSUE THREAD

**Issue by anandsunderraman** [anandsunderraman/jsonsqlonline#9]
query results can be currently downloaded as a csv.
It would be awesome if they could be downloaded as a json file

**Comment by arnabk** [comment]
@anandsunderraman Please assign the task to me

**Comment by anandsunderraman** [comment]
@arnabk go ahead and open a PR

**Comment by arnabk** [comment]
Here you go https://github.com/anandsunderraman/jsonsqlonline/pull/10

**Comment by anandsunderraman** [comment]
Thanks @arnabk
